config/routes.rb
Rails.application.routes.draw do
  devise_for :users 

  resources :friends
  # get 'home/index'
  get "home/about"
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2>
        <%= pluralize(friend.errors.count, "error") %> 
        prohibited this friend from being saved:
      </h2>
      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="m-2 form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>
  <div class="m-2 form-group">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>
  <div class="m-2 form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control" %>
  </div>
  <div class="m-2 form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>
  <div class="m-2 form-group">
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter, class:"form-control" %>
  </div>
  <br>
    <%= form.submit class:"btn btn-primary" %>
<% end %>

app/views/friends/_friend.html.erb
<tr id="<%= dom_id friend %>" scope="row">
  <td scope="col">
    <%= friend.first_name %>
  </td>
  <td scope="col">
    <%= friend.last_name %>
  </td>
  <td scope="col">
    <%= friend.email %>
  </td>
  <td scope="col">
    <%= friend.phone %>
  </td>
  <td scope="col">
    <%= friend.twitter %>
  </td>
  <td scope="col">
    <%= link_to "Show this friend", friend %>
  </td>
</tr>
</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>
<%= render "form", friend: @friend %>
<br>
<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-secondary" %> |
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/index.html.erb
<h1>Friends List</h1>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">
        <strong>First name:</strong>
      </th>
      <th scope="col">
        <strong>Last name:</strong>
      </th>
      <th scope="col">
        <strong>Email:</strong>
      </th>
      <th scope="col">
        <strong>Phone:</strong>
      </th>
      <th scope="col">
        <strong>Twitter:</strong>
      </th>
      <th scope="col">
      </th>
    </tr>
  </thead>
  <tbody>
    <%  @friends.each do |friend| %>
      <%= render friend %>
    <% end %>
  </tbody>
</table>
<%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>
<%= render "form", friend: @friend %>
<br>
<div>
  <%= link_to "Back to friends",
   friends_path,
    class:"btn btn-secondary" %>
</div>

app/views/friends/show.html.erb
<div class="card text-center">
  <div class="card-header">
    <strong><%=  @friend.first_name + " " + @friend.last_name %> </strong>
  </div>
  <div class="card-body">
    <h5 class="card-title">Friend info</h5>
    <p class="card-text">Phone: <%=  @friend.phone %></p>
    <p class="card-text">Email: <%=  @friend.email %></p>
    <p class="card-text">Twitter: <%=  @friend.twitter %></p>
    <%= link_to "Edit this friend",
      edit_friend_path(@friend),
      class:"btn btn-warning m-2" %>
  </div>
  <div class="card-footer text-body-secondary">
    Added 2 days ago
  </div>
</div>
<div>
  <%= link_to "Back to friends", friends_path,
   class:"btn btn-secondary m-2" %>
  <%= button_to "Destroy this friend",
    @friend,
    method: :delete,
    class:"btn btn-danger m-2",
    data: { confirm: "Are you sure?" } %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary dark" >
  <div class="container-fluid">
    <%= link_to "Friends App",
      root_path,
      class:"nav-link active" 
    %>
    <button class="navbar-toggler"
     type="button" data-bs-toggle="collapse"
     data-bs-target="#navbarNav"
     aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
      
       
        <li class="nav-item">
            <%= link_to "About Us",
             home_about_path,
             class:"nav-link" 
             %>
        </li>
        

        <% if user_signed_in? %>
          <li class="nav-item">
              <%= link_to "My friends",
              friends_path,
              class:"nav-link" 
              %>
          </li>
          <li class="nav-item">
              <%= link_to "Add Friend",
              new_friend_path,
              class:"nav-link" 
              %>
          </li>
          <li class="nav-item">
              <%= link_to "Sign Out",
              destroy_user_session_path,
              method: :delete,
              data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
              class:"nav-link" 
              %>
          </li>
          <li class="nav-item">
              <%= link_to "Edit Profile",
              edit_user_registration_path,
              class:"nav-link" 
              %>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to "Sign In",
              new_user_session_path,
              class:"nav-link" 
              %>
          </li>
          
          <li class="nav-item">
              <%= link_to "Sign Up",
              new_user_registration_path,
              class:"nav-link" 
              %>
          </li>
        <% end %>
        
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<h1>My Friends</h1>
<p>My first rails</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <div style="color: green"><%= notice %></div>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  </head>

  <body>
    
    <%= render "home/header" %>
    <div class="container">
      <br/>
      <% if notice %>
        <%= render "layouts/alerts"%>
       <% end %> 
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>